### ISSUE TITLE
Scoring for 0 point games on a card

### ISSUE THREAD

**Issue by heyrocker** [haugstrup/matchplay-issues#4]
I entered a card with one game score (Volley) and 0s for all the others, which you can see here:

https://matchplay.events/live/qkjx/standings

There's an argument to be made that when someone takes a zero score, they should get the lowest possible point value rather than nothing. In this case that would be 73, for a card score of 444. I could probably go either way on this, but it is how I have always run these.

**Comment by haugstrup** [comment]
Hrm, I could also go either way but I'm leaning towards keeping it as it is because it feels wrong to award points for a zero score.

It wasn't a conscious decision, but it's a bit difficult to change at this point because MP will handle tied scores in a best game tournament rather poorly and the likelihood of ties are higher of "0" should be awarded points.

I'm filing an issue to handle ties better in my internal tracker so I don't go crazy
